/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XhiresAmbulanceWlList {
    }
}
declare global {
    interface HTMLXhiresAmbulanceWlListElement extends Components.XhiresAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLXhiresAmbulanceWlListElement: {
        prototype: HTMLXhiresAmbulanceWlListElement;
        new (): HTMLXhiresAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "xhires-ambulance-wl-list": HTMLXhiresAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface XhiresAmbulanceWlList {
    }
    interface IntrinsicElements {
        "xhires-ambulance-wl-list": XhiresAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xhires-ambulance-wl-list": LocalJSX.IntrinsicElements["xhires-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLXhiresAmbulanceWlListElement>;
        }
    }
}
